name: Calculate Folder Checksum

on:
  push:
    branches:
      - main
    paths:
      - 'exposor/intels/**'

jobs:
  calculate-checksum:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Calculate folder checksum and update checksum.json
        run: |
          INTELS_DIR="exposor/intels"
          CHECKSUM_FILE="$INTELS_DIR/checksum.json"

          if [ ! -d "$INTELS_DIR" ]; then
            echo "$INTELS_DIR does not exist"
            exit 1
          fi

          # Calculate folder hash (excluding checksum.json)
          HASH=$(find "$INTELS_DIR" -type f ! -name 'checksum.json' -exec sha256sum {} + | sort | sha256sum | awk '{print $1}')

          # Write to checksum.json
          echo "{ \"intels_hash\": \"$HASH\" }" > "$CHECKSUM_FILE"

      - name: Create Pull Request to update checksum.json
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: auto-update checksum.json"
          title: "chore: update checksum.json"
          body: |
            This PR was automatically generated by GitHub Actions after changes were pushed to `intels/`.

            It updates `checksum.json` with the latest hash of the folder contents.
          branch: "auto/update-checksum-${{ github.run_id }}"
          base: main
